// Import necessary functions from Redux Toolkit
import { configureStore, createSlice } from '@reduxjs/toolkit';

// Create a Redux Toolkit slice for managing authentication state
const authSlice = createSlice({
    name: 'auth', // The name of the slice
    initialState: { isLoggedIn: false }, // Initial state for the slice
    reducers: {
        login(state)
        {
            state.isLoggedIn = true; // Reducer function for the 'login' action
        },
        logout(state)
        {
            state.isLoggedIn = false; // Reducer function for the 'logout' action
        }
    }
});

// Export the action creators generated by the 'createSlice' function
export const authActions = authSlice.actions;

// Configure the Redux store with the 'authSlice' reducer
export const store = configureStore({
    reducer: authSlice.reducer // The reducer for the store
});
